[package]
name = "xdsim-dummy-bit-data"
version = "0.1.2"
edition = "2024"

[dependencies]
libxdsim = { git = "https://github.com/25cst/libxdsim" }
# libxdsim = { path = "../libxdsim/" }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
export-abi = []
